wandb_version: 1

convSize:
  value: 512
dropOut:
  value: 0.3
epochs:
  value: 1
epochs_steps:
  value: 1
init_learning_rate:
  value: 0.021865961111437945
leakyR1:
  value: 0.8852062277192789
leakyR2:
  value: 0.906640859633108
lstm1Size:
  value: 512
lstm2Size:
  value: 16
