wandb_version: 1

convSize:
  value: 512
dropOut:
  value: 0.4
epochs:
  value: 1
epochs_steps:
  value: 1
init_learning_rate:
  value: 0.03897213980790543
leakyR1:
  value: 0.4155953793822529
leakyR2:
  value: 0.16348313519398985
lstm1Size:
  value: 64
lstm2Size:
  value: 64
