wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648589020
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 4
      - 5
convSize:
  desc: null
  value: 186.47619166685004
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 100
epochs_steps:
  desc: null
  value: 200
init_learning_rate:
  desc: null
  value: 0.009133107413052316
leakyR1:
  desc: null
  value: 0.044934660882669175
leakyR2:
  desc: null
  value: 0.006656066954388029
lstm1Size:
  desc: null
  value: 333.6554341514902
lstm2Size:
  desc: null
  value: 432.81089391843193
