wandb_version: 1

convSize:
  value: 16
dropOut:
  value: 0.1
epochs:
  value: 1
epochs_steps:
  value: 1
init_learning_rate:
  value: 0.006312594921528849
leakyR1:
  value: 0.100684453048146
leakyR2:
  value: 0.698184382399625
lstm1Size:
  value: 128
lstm2Size:
  value: 512
