wandb_version: 1

convSize:
  value: 64
dropOut:
  value: 0.3
epochs:
  value: 1
epochs_steps:
  value: 1
init_learning_rate:
  value: 0.0796703876988408
leakyR1:
  value: 0.7332374472033866
leakyR2:
  value: 0.4118740924683302
lstm1Size:
  value: 128
lstm2Size:
  value: 16
