wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648589366
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 5
convSize:
  desc: null
  value: 64
dropOut:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 1
epochs_steps:
  desc: null
  value: 1
init_learning_rate:
  desc: null
  value: 0.0796703876988408
leakyR1:
  desc: null
  value: 0.7332374472033866
leakyR2:
  desc: null
  value: 0.4118740924683302
lstm1Size:
  desc: null
  value: 128
lstm2Size:
  desc: null
  value: 16
