wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648589260
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 5
convSize:
  desc: null
  value: 16
dropOut:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 1
epochs_steps:
  desc: null
  value: 1
init_learning_rate:
  desc: null
  value: 0.006312594921528849
leakyR1:
  desc: null
  value: 0.100684453048146
leakyR2:
  desc: null
  value: 0.698184382399625
lstm1Size:
  desc: null
  value: 128
lstm2Size:
  desc: null
  value: 512
