wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648588936
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 4
      - 5
convSize:
  desc: null
  value: 16.3464882965877
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 100
epochs_steps:
  desc: null
  value: 10
init_learning_rate:
  desc: null
  value: 0.0713259079224228
leakyR1:
  desc: null
  value: 0.24344141782042591
leakyR2:
  desc: null
  value: 0.9124035425709156
lstm1Size:
  desc: null
  value: 444.1816555614104
lstm2Size:
  desc: null
  value: 60.81904181773425
