wandb_version: 1

convSize:
  value: 64
dropOut:
  value: 0.4
epochs:
  value: 1
epochs_steps:
  value: 1
init_learning_rate:
  value: 0.019532938536304584
leakyR1:
  value: 0.7799464247931225
leakyR2:
  value: 0.7632877278133114
lstm1Size:
  value: 64
lstm2Size:
  value: 128
