wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648625437
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 4
      - 5
convSize:
  desc: null
  value: 16
dropOut:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 50
epochs_steps:
  desc: null
  value: 100
init_learning_rate:
  desc: null
  value: 0.022961417989859463
leakyR1:
  desc: null
  value: 0.14322875683653324
leakyR2:
  desc: null
  value: 0.59221584673171
lstm1Size:
  desc: null
  value: 32
lstm2Size:
  desc: null
  value: 64
