wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1648589046
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.12
      5: 0.12.11
      8:
      - 1
      - 4
      - 5
convSize:
  desc: null
  value: 228.78015699977928
dropOut:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 500
epochs_steps:
  desc: null
  value: 200
init_learning_rate:
  desc: null
  value: 0.07797338262155804
leakyR1:
  desc: null
  value: 0.2613280300189772
leakyR2:
  desc: null
  value: 0.4988878681449592
lstm1Size:
  desc: null
  value: 190.5802449063198
lstm2Size:
  desc: null
  value: 132.11111261619538
